// Code generated by mockery v2.53.5. DO NOT EDIT.

package client

import mock "github.com/stretchr/testify/mock"

// MockEcoSystemV3beta1Interface is an autogenerated mock type for the EcoSystemV3beta1Interface type
type MockEcoSystemV3beta1Interface struct {
	mock.Mock
}

type MockEcoSystemV3beta1Interface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEcoSystemV3beta1Interface) EXPECT() *MockEcoSystemV3beta1Interface_Expecter {
	return &MockEcoSystemV3beta1Interface_Expecter{mock: &_m.Mock}
}

// Dogus provides a mock function with given fields: namespace
func (_m *MockEcoSystemV3beta1Interface) Dogus(namespace string) DoguV3beta1Interface {
	ret := _m.Called(namespace)

	if len(ret) == 0 {
		panic("no return value specified for Dogus")
	}

	var r0 DoguV3beta1Interface
	if rf, ok := ret.Get(0).(func(string) DoguV3beta1Interface); ok {
		r0 = rf(namespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(DoguV3beta1Interface)
		}
	}

	return r0
}

// MockEcoSystemV3beta1Interface_Dogus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dogus'
type MockEcoSystemV3beta1Interface_Dogus_Call struct {
	*mock.Call
}

// Dogus is a helper method to define mock.On call
//   - namespace string
func (_e *MockEcoSystemV3beta1Interface_Expecter) Dogus(namespace interface{}) *MockEcoSystemV3beta1Interface_Dogus_Call {
	return &MockEcoSystemV3beta1Interface_Dogus_Call{Call: _e.mock.On("Dogus", namespace)}
}

func (_c *MockEcoSystemV3beta1Interface_Dogus_Call) Run(run func(namespace string)) *MockEcoSystemV3beta1Interface_Dogus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockEcoSystemV3beta1Interface_Dogus_Call) Return(_a0 DoguV3beta1Interface) *MockEcoSystemV3beta1Interface_Dogus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEcoSystemV3beta1Interface_Dogus_Call) RunAndReturn(run func(string) DoguV3beta1Interface) *MockEcoSystemV3beta1Interface_Dogus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEcoSystemV3beta1Interface creates a new instance of MockEcoSystemV3beta1Interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEcoSystemV3beta1Interface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEcoSystemV3beta1Interface {
	mock := &MockEcoSystemV3beta1Interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
