// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3beta1 "github.com/cloudogu/k8s-dogu-lib/v2/api/v3beta1"
	apiv3beta1 "github.com/cloudogu/k8s-dogu-lib/v2/client/typed/api/v3beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeDogus implements DoguInterface
type fakeDogus struct {
	*gentype.FakeClientWithList[*v3beta1.Dogu, *v3beta1.DoguList]
	Fake *FakeDoguV3beta1
}

func newFakeDogus(fake *FakeDoguV3beta1, namespace string) apiv3beta1.DoguInterface {
	return &fakeDogus{
		gentype.NewFakeClientWithList[*v3beta1.Dogu, *v3beta1.DoguList](
			fake.Fake,
			namespace,
			v3beta1.SchemeGroupVersion.WithResource("dogus"),
			v3beta1.SchemeGroupVersion.WithKind("Dogu"),
			func() *v3beta1.Dogu { return &v3beta1.Dogu{} },
			func() *v3beta1.DoguList { return &v3beta1.DoguList{} },
			func(dst, src *v3beta1.DoguList) { dst.ListMeta = src.ListMeta },
			func(list *v3beta1.DoguList) []*v3beta1.Dogu { return gentype.ToPointerSlice(list.Items) },
			func(list *v3beta1.DoguList, items []*v3beta1.Dogu) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
