// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3beta1 "github.com/cloudogu/k8s-dogu-lib/v3/client/typed/api/v3beta1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeDoguV3beta1 struct {
	*testing.Fake
}

func (c *FakeDoguV3beta1) Dogus(namespace string) v3beta1.DoguInterface {
	return newFakeDogus(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeDoguV3beta1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
