// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2 "github.com/cloudogu/k8s-dogu-lib/v3/client/typed/api/v2"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeDoguV2 struct {
	*testing.Fake
}

func (c *FakeDoguV2) Dogus(namespace string) v2.DoguInterface {
	return newFakeDogus(c, namespace)
}

func (c *FakeDoguV2) DoguRestarts(namespace string) v2.DoguRestartInterface {
	return newFakeDoguRestarts(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeDoguV2) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
