// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2 "github.com/cloudogu/k8s-dogu-lib/v3/api/v2"
	apiv2 "github.com/cloudogu/k8s-dogu-lib/v3/client/typed/api/v2"
	gentype "k8s.io/client-go/gentype"
)

// fakeDoguRestarts implements DoguRestartInterface
type fakeDoguRestarts struct {
	*gentype.FakeClientWithList[*v2.DoguRestart, *v2.DoguRestartList]
	Fake *FakeDoguV2
}

func newFakeDoguRestarts(fake *FakeDoguV2, namespace string) apiv2.DoguRestartInterface {
	return &fakeDoguRestarts{
		gentype.NewFakeClientWithList[*v2.DoguRestart, *v2.DoguRestartList](
			fake.Fake,
			namespace,
			v2.SchemeGroupVersion.WithResource("dogurestarts"),
			v2.SchemeGroupVersion.WithKind("DoguRestart"),
			func() *v2.DoguRestart { return &v2.DoguRestart{} },
			func() *v2.DoguRestartList { return &v2.DoguRestartList{} },
			func(dst, src *v2.DoguRestartList) { dst.ListMeta = src.ListMeta },
			func(list *v2.DoguRestartList) []*v2.DoguRestart { return gentype.ToPointerSlice(list.Items) },
			func(list *v2.DoguRestartList, items []*v2.DoguRestart) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
