// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2 "github.com/cloudogu/k8s-dogu-lib/v2/api/v2"
	apiv2 "github.com/cloudogu/k8s-dogu-lib/v2/client/typed/api/v2"
	gentype "k8s.io/client-go/gentype"
)

// fakeDogus implements DoguInterface
type fakeDogus struct {
	*gentype.FakeClientWithList[*v2.Dogu, *v2.DoguList]
	Fake *FakeDoguV2
}

func newFakeDogus(fake *FakeDoguV2, namespace string) apiv2.DoguInterface {
	return &fakeDogus{
		gentype.NewFakeClientWithList[*v2.Dogu, *v2.DoguList](
			fake.Fake,
			namespace,
			v2.SchemeGroupVersion.WithResource("dogus"),
			v2.SchemeGroupVersion.WithKind("Dogu"),
			func() *v2.Dogu { return &v2.Dogu{} },
			func() *v2.DoguList { return &v2.DoguList{} },
			func(dst, src *v2.DoguList) { dst.ListMeta = src.ListMeta },
			func(list *v2.DoguList) []*v2.Dogu { return gentype.ToPointerSlice(list.Items) },
			func(list *v2.DoguList, items []*v2.Dogu) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
