// Code generated by client-gen. DO NOT EDIT.

package v2

import (
	context "context"

	apiv2 "github.com/cloudogu/k8s-dogu-lib/v2/api/v2"
	scheme "github.com/cloudogu/k8s-dogu-lib/v2/client/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DoguRestartsGetter has a method to return a DoguRestartInterface.
// A group's client should implement this interface.
type DoguRestartsGetter interface {
	DoguRestarts(namespace string) DoguRestartInterface
}

// DoguRestartInterface has methods to work with DoguRestart resources.
type DoguRestartInterface interface {
	Create(ctx context.Context, doguRestart *apiv2.DoguRestart, opts v1.CreateOptions) (*apiv2.DoguRestart, error)
	Update(ctx context.Context, doguRestart *apiv2.DoguRestart, opts v1.UpdateOptions) (*apiv2.DoguRestart, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, doguRestart *apiv2.DoguRestart, opts v1.UpdateOptions) (*apiv2.DoguRestart, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv2.DoguRestart, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv2.DoguRestartList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv2.DoguRestart, err error)
	DoguRestartExpansion
}

// doguRestarts implements DoguRestartInterface
type doguRestarts struct {
	*gentype.ClientWithList[*apiv2.DoguRestart, *apiv2.DoguRestartList]
}

// newDoguRestarts returns a DoguRestarts
func newDoguRestarts(c *DoguV2Client, namespace string) *doguRestarts {
	return &doguRestarts{
		gentype.NewClientWithList[*apiv2.DoguRestart, *apiv2.DoguRestartList](
			"dogurestarts",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv2.DoguRestart { return &apiv2.DoguRestart{} },
			func() *apiv2.DoguRestartList { return &apiv2.DoguRestartList{} },
		),
	}
}
