// Code generated by client-gen. DO NOT EDIT.

package v2

import (
	context "context"

	apiv2 "github.com/cloudogu/k8s-dogu-lib/v3/api/v2"
	scheme "github.com/cloudogu/k8s-dogu-lib/v3/client/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DogusGetter has a method to return a DoguInterface.
// A group's client should implement this interface.
type DogusGetter interface {
	Dogus(namespace string) DoguInterface
}

// DoguInterface has methods to work with Dogu resources.
type DoguInterface interface {
	Create(ctx context.Context, dogu *apiv2.Dogu, opts v1.CreateOptions) (*apiv2.Dogu, error)
	Update(ctx context.Context, dogu *apiv2.Dogu, opts v1.UpdateOptions) (*apiv2.Dogu, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, dogu *apiv2.Dogu, opts v1.UpdateOptions) (*apiv2.Dogu, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv2.Dogu, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv2.DoguList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv2.Dogu, err error)
	DoguExpansion
}

// dogus implements DoguInterface
type dogus struct {
	*gentype.ClientWithList[*apiv2.Dogu, *apiv2.DoguList]
}

// newDogus returns a Dogus
func newDogus(c *DoguV2Client, namespace string) *dogus {
	return &dogus{
		gentype.NewClientWithList[*apiv2.Dogu, *apiv2.DoguList](
			"dogus",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv2.Dogu { return &apiv2.Dogu{} },
			func() *apiv2.DoguList { return &apiv2.DoguList{} },
		),
	}
}
