// Code generated by client-gen. DO NOT EDIT.

package v3beta1

import (
	http "net/http"

	apiv3beta1 "github.com/cloudogu/k8s-dogu-lib/v2/api/v3beta1"
	scheme "github.com/cloudogu/k8s-dogu-lib/v2/client/scheme"
	rest "k8s.io/client-go/rest"
)

type DoguV3beta1Interface interface {
	RESTClient() rest.Interface
	DogusGetter
}

// DoguV3beta1Client is used to interact with features provided by the k8s.cloudogu.com group.
type DoguV3beta1Client struct {
	restClient rest.Interface
}

func (c *DoguV3beta1Client) Dogus(namespace string) DoguInterface {
	return newDogus(c, namespace)
}

// NewForConfig creates a new DoguV3beta1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*DoguV3beta1Client, error) {
	config := *c
	setConfigDefaults(&config)
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new DoguV3beta1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*DoguV3beta1Client, error) {
	config := *c
	setConfigDefaults(&config)
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &DoguV3beta1Client{client}, nil
}

// NewForConfigOrDie creates a new DoguV3beta1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *DoguV3beta1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new DoguV3beta1Client for the given RESTClient.
func New(c rest.Interface) *DoguV3beta1Client {
	return &DoguV3beta1Client{c}
}

func setConfigDefaults(config *rest.Config) {
	gv := apiv3beta1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *DoguV3beta1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
